# Generated by Django 2.2.5 on 2019-09-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('s_name', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('salary', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
